#!/usr/bin/env ruby

require 'trabox/command'

$stdout.sync = true
$stderr.sync = true

command_parser = Trabox::Command::Parser.new
begin
  command = command_parser.parse!

  require 'trabox/runner'
  Trabox::Command.invoke command
rescue StandardError => e
  warn e.backtrace
  warn ""
  warn command_parser.usage
  exit 1
end

# vim:ft=ruby:
