name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd 'mysqladmin ping'
          --health-interval 10s
          --health-timeout 5
          --health-retry 5

    env:
      PUBSUB_TOPIC_ID: trabox
      PUBSUB_SUBSCRIPTION_ID: trabox-sub
      PUBSUB_EMULATOR_HOST: localhost:8085
      GOOGLE_CLOUD_PROJECT: trabox
      MYSQL_HOST: mysql
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: "pubsub-emulator"

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Set up database
        run: bin/setup-db

      - name: Run tests
        run: |
          gcloud beta emulators pubsub start --host-port=localhost:8085 &
          curl http://localhost:8085 --silent --retry 30 --retry-delay 1 --retry-connrefused
          bin/rspec
